
name: 'Docker Stack Deploy Action'
description: 'Deploy a Docker stack on a Docker Swarm'
author: 'kitconcept GmbH'
branding:
  icon: 'truck'
  color: 'red'
inputs:
  registry:
    description: 'Container registry to use'
    required: false
    default: ""
  registry_username:
    description: 'Container registry username'
    required: false
    default: ""
  registry_password:
    description: 'Container registry password'
    required: false
    default: ""
  remote_host:
    description: 'Host running Docker Swarm'
    required: true
  remote_port:
    description: 'port on the host running Docker Swarm'
    required: false
    default: "22"
  remote_ca:
    description: 'User to connect to remote host'
    required: true
  remote_certificate:
    description: 'Certificate to present'
    required: true
  remote_private_key:
    description: 'Private key used for ssh authentication'
    required: true
  deploy_timeout:
    description: "Timeout for the deploy check (in seconds)"
    required: false
    default: "600"
  stack_file:
    description: "Path to the stack file to be used for deploy"
    required: true
  stack_name:
    description: "Name of the stack to be deployed"
    required: true
  stack_param:
    description: "Additional stack parameter value"
    required: false
    default: ""
  env_file:
    description: "Additional environment variables in the format VAR_01=VALUE\nVAR_02=VALUE"
    required: false
    default: ""
  debug:
    description: "Debug information"
    required: false
    default: "0"
runs:
  using: 'docker'
  image: 'docker://dresttech/docker-stack-deploy:tls'
  env:
    REGISTRY: ${{ inputs.registry }}
    USERNAME: ${{ inputs.registry_username }}
    PASSWORD: ${{ inputs.registry_password }}
    REMOTE_HOST: ${{ inputs.remote_host }}
    REMOTE_PORT: ${{ inputs.remote_port }}
    REMOTE_CA: ${{ inputs.remote_ca }}
    REMOTE_CERTIFICATE: ${{ inputs.remote_certificate }}
    REMOTE_PRIVATE_KEY: ${{ inputs.remote_private_key }}
    DEPLOY_TIMEOUT: ${{ inputs.deploy_timeout }}
    STACK_FILE: ${{ inputs.stack_file }}
    STACK_NAME: ${{ inputs.stack_name }}
    STACK_PARAM: ${{ inputs.stack_param }}
    ENV_FILE: ${{ inputs.env_file }}
    DEBUG: ${{ inputs.debug }}
